---
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: CUSTOMER_A
    # Number used to generate the VNI of each VLAN by adding the VLAN number in this tenant.
    mac_vrf_vni_base: 10000
    vrfs:
      # VRF definition
      - name: VRF_10
        # VRF VNI definition
        vrf_vni: 10
        # Enable VTEP Network diagnostics
        # This will create a loopback with virtual source-nat enable to perform diagnostics from the switch.
        vtep_diagnostic:
          # Loopback interface
          loopback: 10
          # Loopback ip range, a unique ip is derived from this ranged and assigned
          # to each l3 leaf based on it's unique id.
          loopback_ip_range: 10.255.10.0/27
        svis:
          # SVI definitions
          - id: 11
            # SVI description
            name: VRF_10_VLAN_11
            enabled: true
            # IP anycast gateway 
            ip_address_virtual: 10.10.11.1/24
            tags:
              - pod1
          - id: 12
            name: VRF_10_VLAN_12
            enabled: true
            ip_address_virtual: 10.10.12.1/24
            tags:
              - pod1
          - id: 21
            name: VRF_10_VLAN_21
            enabled: true
            ip_address_virtual: 10.10.21.1/24
            tags:
              - pod2
          - id: 22
            name: VRF_10_VLAN_22
            enabled: true
            ip_address_virtual: 10.10.22.1/24
            tags:
              - pod2